// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://toigsarjwwediuelpxvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvaWdzYXJqd3dlZGl1ZWxweHZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1MjEyNTUsImV4cCI6MjA1NzA5NzI1NX0.FRc7qqt5Q76k1EPGAdYAQh51Wbmg2wzED2uLJVuhaas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);